apiVersion: v1
kind: Service
metadata:
  name: digitaloceanchallengeserversvc
spec:
  type: NodePort
  selector:
    name: digitaloceanchallengeserver
  ports:
    - name: http
      protocol: TCP
      nodePort: 30012
      port: 3000
      targetPort: 3000
    - name: websocket
      protocol: TCP
      nodePort: 30013
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: digitaloceanchallengeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: digitaloceanchallengeserver
  template:
    metadata:
      labels:
        name: digitaloceanchallengeserver
    spec:
      containers:
        - name: digitaloceanchallengeserver
          image: sossenbinder/digitaloceanchallengeserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 8080
              name: websocket
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
          env:
            - name: KAFKA_CONNECTION
              value: "digitaloceancluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
