kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: digitaloceanchallenge
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://kindRegistry:5000"]
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8085
      - containerPort: 30012
        hostPort: 30012
      - containerPort: 30013
        hostPort: 30013
