# Expose all ports required by the setup for good measure
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: digitaloceanchallenge
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8085
      - containerPort: 30012
        hostPort: 30012
      - containerPort: 30013
        hostPort: 30013
      - containerPort: 30015
        hostPort: 30015
