# For dev, I wanted to expose the ports through k8s to the local react app
apiVersion: v1
kind: Service
metadata:
  name: digitaloceanchallengeserver
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      nodePort: 30012
      port: 3000
      targetPort: 3000
    - name: websocket
      protocol: TCP
      nodePort: 30013
      port: 8080
      targetPort: 8080
